import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { DonorProfile, NGO, ThalassemiaPatient, InventoryItem } from '../types';

export const exportToCSV = (data: any[], fileName: string) => {
  if (data.length === 0) return;
  
  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(','),
    ...data.map(row => headers.map(header => {
      const val = row[header];
      return `"${val !== undefined ? val : ''}"`;
    }).join(','))
  ];
  
  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `${fileName}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportDonorsToPDF = (donors: DonorProfile[], ngo: NGO | undefined, systemLogo: string | null) => {
  const doc = new jsPDF();
  const ngoName = ngo?.name || 'Blood Dost';
  const ngoEmail = 'contact@blooddost.com'; 
  const ngoAddress = ngo?.address || 'Balochistan, Pakistan';

  // --- 1. Letterhead Branding ---
  // System Logo (Top Right)
  if (systemLogo) {
    try {
      doc.addImage(systemLogo, 'JPEG', 170, 10, 25, 25, undefined, 'FAST');
    } catch (e) { console.warn(e); }
  } else {
    doc.setFillColor(239, 68, 68); 
    doc.rect(180, 15, 12, 12, 'F');
  }

  // NGO Logo (Top Left)
  if (ngo?.logo) {
    try {
      doc.addImage(ngo.logo, 'JPEG', 15, 10, 25, 25, undefined, 'FAST');
    } catch (e) {
      console.warn(e);
      doc.setFillColor(239, 68, 68); 
      doc.rect(15, 15, 12, 12, 'F');
    }
  } else {
    doc.setFillColor(239, 68, 68); 
    doc.rect(15, 15, 12, 12, 'F');
  }
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(30, 41, 59); 
  doc.text(ngoName, 45, 23);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); 
  doc.text(`${ngoAddress} | Phone: ${ngo?.phone || 'N/A'}`, 45, 28);
  
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.line(15, 35, 195, 35);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.text('Donor List Report', 15, 45);
  
  // Simple Watermark
  doc.setFontSize(50);
  doc.setTextColor(240, 240, 240);
  doc.text(ngoName, 40, 150, { angle: 45 });

  // --- 2. Data Table ---
  const tableData = donors.map((d, index) => [
    index + 1,
    d.name,
    d.bloodGroup,
    d.phone,
    d.location.district || 'N/A',
    d.lastDonated ? new Date(d.lastDonated).toLocaleDateString() : 'Never'
  ]);

  autoTable(doc, {
    startY: 52,
    head: [['#', 'Name', 'Blood Group', 'Phone', 'District', 'Last Donated']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { top: 50 },
    styles: { fontSize: 9, cellPadding: 3 },
  });

  // --- 3. Footer ---
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(`Page ${i} of ${pageCount}`, 15, 285);
    doc.text(`Generated on: ${new Date().toLocaleString()} | Generated by Blood Dost`, 195, 285, { align: 'right' });
  }

  doc.save(`${ngoName.replace(/\s/g, '_')}_Donors.pdf`);
};

export const exportPatientsToPDF = (patients: ThalassemiaPatient[], ngo: NGO | undefined, systemLogo: string | null) => {
    const doc = new jsPDF();
    const ngoName = ngo?.name || 'Blood Dost';
    const ngoAddress = ngo?.address || 'Balochistan, Pakistan';
  
    // Header - NGO Logo
    if (ngo?.logo) {
      try {
        doc.addImage(ngo.logo, 'JPEG', 15, 10, 25, 25);
      } catch(e) {
        doc.setFillColor(239, 68, 68);
        doc.rect(15, 15, 12, 12, 'F');
      }
    } else {
      doc.setFillColor(239, 68, 68);
      doc.rect(15, 15, 12, 12, 'F');
    }

    // Header - System Logo
    if (systemLogo) {
      try {
        doc.addImage(systemLogo, 'JPEG', 170, 10, 25, 25);
      } catch(e) {}
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59);
    doc.text(ngoName, 45, 23);
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`${ngoAddress} | Phone: ${ngo?.phone || 'N/A'}`, 45, 28);
    doc.line(15, 35, 195, 35);
  
    // Report Title
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59);
    doc.text('Thalassemia Patients Report', 15, 45);

    const tableData = patients.map((p, index) => {
      const last = new Date(p.lastTransfusion);
      const next = new Date(last.getTime() + p.cycleDays * 24 * 60 * 60 * 1000);
      return [
        index + 1,
        p.name,
        p.fatherName,
        p.bloodGroup,
        p.age,
        p.hospital,
        p.contactNumber,
        new Date(p.lastTransfusion).toLocaleDateString(),
        next.toLocaleDateString()
      ];
    });
  
    autoTable(doc, {
      startY: 52,
      head: [['#', 'Name', 'Father', 'Group', 'Age', 'Hospital', 'Contact', 'Last', 'Next Due']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontSize: 8 },
      margin: { top: 50 },
      styles: { fontSize: 7 }
    });
  
    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Page ${i} of ${pageCount}`, 15, 285);
      doc.text(`Generated on: ${new Date().toLocaleString()} | Generated by Blood Dost`, 195, 285, { align: 'right' });
    }
  
    doc.save(`${ngoName.replace(/\s/g, '_')}_Patients.pdf`);
  };

export const exportSuperAdminReportPDF = (summary: any, ngos: NGO[], systemLogo: string | null) => {
  const doc = new jsPDF();
  
  // --- Header ---
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.rect(0, 0, 210, 40, 'F');
  
  if (systemLogo) {
    try {
      doc.addImage(systemLogo, 'JPEG', 15, 10, 25, 25);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(28);
      doc.setTextColor(255, 255, 255);
      doc.text('BLOOD DOST', 45, 25);
    } catch (e) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(28);
      doc.setTextColor(255, 255, 255);
      doc.text('BLOOD DOST', 15, 25);
    }
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.setTextColor(255, 255, 255);
    doc.text('BLOOD DOST', 15, 25);
  }
  
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text('MASTER SYSTEM ANALYTICS & NGO REPORT', systemLogo ? 45 : 15, 32);
  
  // Title
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text('System Summary Report', 15, 55);
  
  // Analytics Box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(15, 60, 180, 40, 3, 3, 'F');
  
  doc.setFontSize(10);
  doc.text('Total System Donors:', 25, 75);
  doc.text(String(summary.totalDonors), 80, 75);
  
  doc.text('Total Registered NGOs:', 25, 82);
  doc.text(String(summary.ngoCount), 80, 82);
  
  doc.text('Active Subscriptions:', 25, 89);
  doc.text(String(summary.activeNGOs), 80, 89);
  
  doc.text('Expired Subscriptions:', 120, 75);
  doc.text(String(summary.expiredNGOs), 160, 75);

  // NGO Listing Title
  doc.setFontSize(14);
  doc.text('Registered Operations', 15, 115);

  const tableData = ngos.map((n, i) => [
    i + 1,
    n.name,
    n.district || 'All Districts',
    n.donorLimit || '1000',
    n.phone
  ]);

  autoTable(doc, {
    startY: 120,
    head: [['#', 'NGO Name', 'Operation District', 'Donor Limit', 'Contact']],
    body: tableData,
    headStyles: { fillColor: [15, 23, 42] }
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`BLOOD DOST - CONFIDENTIAL SUPER ADMIN REPORT`, 15, 285);
    doc.text(`Page ${i}/${pageCount} | Generated: ${new Date().toLocaleString()}`, 195, 285, { align: 'right' });
  }

  doc.save(`SuperAdmin_MasterReport_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const exportNGOMonitorReportPDF = (ngo: NGO, donors: DonorProfile[], inventory: InventoryItem[], patients: ThalassemiaPatient[]) => {
  const doc = new jsPDF();
  const ngoName = ngo.name;
  
  // Header section
  doc.setFillColor(15, 23, 42); 
  doc.rect(0, 0, 210, 35, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(ngoName, 15, 22);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`${ngo.address} | Phone: ${ngo.phone}`, 15, 28);
  
  // Stats Summary
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text('Data Audit Summary', 15, 50);
  
  const stats = [
    { label: 'Total Donors', value: donors.length },
    { label: 'Total Patients', value: patients.length },
    { label: 'Inventory Units', value: inventory.reduce((acc, curr) => acc + curr.units, 0) }
  ];
  
  doc.setFontSize(10);
  stats.forEach((stat, i) => {
    doc.text(`${stat.label}: ${stat.value}`, 15, 60 + (i * 7));
  });
  
  // Donors Table
  doc.setFontSize(14);
  doc.text('Registered Donors', 15, 90);
  
  autoTable(doc, {
    startY: 95,
    head: [['#', 'Name', 'Blood Group', 'Phone', 'Address']],
    body: donors.map((d, i) => [i + 1, d.name, d.bloodGroup, d.phone, d.location.address]),
    headStyles: { fillColor: [239, 68, 68] },
    margin: { bottom: 20 },
    styles: { fontSize: 8 }
  });
  
  // Inventory Table
  const finalY = (doc as any).lastAutoTable.finalY || 100;
  doc.setFontSize(14);
  doc.text('Blood Inventory', 15, finalY + 15);
  
  autoTable(doc, {
    startY: finalY + 20,
    head: [['Blood Group', 'Available Units']],
    body: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map(bg => {
      const count = inventory.filter(i => i.bloodGroup === bg).reduce((acc, curr) => acc + curr.units, 0);
      return [bg, count];
    }),
    headStyles: { fillColor: [37, 99, 235] },
    margin: { bottom: 20 },
    styles: { fontSize: 8 }
  });
  
  // Patients Table
  const lastY = (doc as any).lastAutoTable.finalY || 200;
  doc.setFontSize(14);
  doc.text('Thalassemia Patients', 15, lastY + 15);
  
  autoTable(doc, {
    startY: lastY + 20,
    head: [['#', 'Name', 'Blood Group', 'Contact', 'Hospital']],
    body: patients.map((p, i) => [i + 1, p.name, p.bloodGroup, p.contactNumber, p.hospital]),
    headStyles: { fillColor: [15, 23, 42] },
    margin: { bottom: 20 },
    styles: { fontSize: 8 }
  });
  
  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`NGO DATA AUDIT REPORT | Page ${i} of ${pageCount}`, 15, 285);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 195, 285, { align: 'right' });
  }
  
  doc.save(`${ngoName.replace(/\s/g, '_')}_FullAudit.pdf`);
};


